title: Hanzo Browser Extension
description: AI-powered browser extension for Chrome, Firefox, Edge, Safari
url: https://hanzoai.github.io
baseurl: /browser-extension
remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme

defaults:
  - scope:
      path: ""
    values:
      layout: default
